### ISSUE TITLE
ModuleNotFound

### ISSUE THREAD

**Issue by yogeshwari-20000609** [darrenjkt/VCN#2]
Hi your work seems so nice.  I'am actually trying to test your model. But i think some files are missing in utils(). For details you can see below screenshot.
![Screenshot from 2023-02-23 17-18-09](https://user-images.githubusercontent.com/56786259/220897533-0712b94c-f82c-47c9-8dd2-89b0b472e493.png)
Can you please provide necessary modules ASAP.

**Comment by darrenjkt** [comment]
You can run these two lines without the "RUN" keyword to install those modules.

https://github.com/darrenjkt/VCN/blob/44c0ca40d90645fbd9b124394cbc99fd303810ce/docker/Dockerfile#L26-L28

You can also just build the docker image and it should work
